version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
      POSTGRES_DB: smarttasks
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # scheduler
  # worker

  web:
    image: python:3.11-slim
    working_dir: /app
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app
    environment:
      - DB_USER=smartuser
      - DB_PASSWORD=smartpass
      - DB_NAME=smarttasks
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
